import type { ConsoleData, ConsoleRecord, SectionId } from './console-model';
// Deliberately synthetic, server-loaded fixtures. Never a fallback for a failed live request.
const time = '2026-09-11T14:35:00.000Z';
const record = (id: string, title: string, category: string, status: string, owner: string, fields: Record<string, string>, tone: ConsoleRecord['tone'] = 'neutral'): ConsoleRecord => ({ id, title, subtitle: id.toUpperCase(), category, status, owner, fields, tone, updatedAt: time });
const customer = record('demo-customer-001', 'Amina K.', 'Personal', 'Verified', 'Core', { 'Customer reference': 'DEMO-CUSTOMER-001', 'Phone': '+225 •• •• 3456', 'Country': "Côte d’Ivoire", 'KYC level': 'Full', 'Core status': 'Active', 'Accounts': 'Current + savings', 'Available balance': 'XOF 125,000 · synthetic', 'Partner reference': 'DEMO-REF-001', 'Identity': 'Verified linkage', 'Agency': 'Abidjan · demo' }, 'success');
customer.related = [{ label: 'Investigate payment', section: 'payments', id: 'demo-payment-001' }, { label: 'Review credit evidence', section: 'credit', id: 'demo-score-001' }, { label: 'View aliases', section: 'aliases' }, { label: 'Open cases', section: 'inbox' }];
customer.timeline = [{ title: 'Payment callback received', detail: 'Provider success; Core posting still pending', time }, { title: 'Credit evidence reviewed', detail: 'Evidence review is not loan approval', time: '2026-09-11T12:10:00Z' }, { title: 'KYC verified', detail: 'Synthetic identity record', time: '2026-09-10T09:15:00Z' }];
const payment = record('demo-payment-001', 'Mobile Money deposit', 'Payin', 'Reconciliation', 'Payment Gateway', { 'Customer': 'Amina K. · demo', 'Amount': 'XOF 25,000', 'Provider': 'Provider A · synthetic', 'Channel': 'Mobile app', 'Core reference': 'DEMO-CORE-001', 'Gateway reference': 'DEMO-GW-001', 'Provider reference': 'DEMO-PROVIDER-001', 'Idempotency': 'DEMO-IDEMPOTENCY-001', 'Financial posting': 'Not completed' }, 'warning');
payment.owners = [{ owner: 'Mobile channel', state: 'preview', status: 'Submitted', observedAt: time }, { owner: 'Core', state: 'preview', status: 'Pending posting', observedAt: time }, { owner: 'Payment Gateway', state: 'preview', status: 'Provider confirmed', observedAt: time }, { owner: 'Financial ledger', state: 'preview', status: 'Not completed', observedAt: time }];
payment.timeline = [{ title: 'Initiated', detail: 'Idempotent request accepted', time: '2026-09-11T14:32:00Z' }, { title: 'Provider processing', detail: 'Provider reference assigned', time: '2026-09-11T14:33:00Z' }, { title: 'Callback received', detail: 'Provider success is not ledger completion', time }, { title: 'Reconciliation required', detail: 'No financial action is executed by this preview', time }];
payment.related = [{ label: 'Customer workspace', section: 'customers', id: customer.id }, { label: 'Investigation case', section: 'inbox', id: 'demo-case-001' }];
const score = record('demo-score-001', 'Amina K. · credit assessment', 'Review', 'Needs evidence', 'Credit Intelligence', { 'Score': '720 / 1,200 · synthetic', 'Model version': 'DEMO-MODEL-1', 'Requested amount': 'XOF 75,000', 'Evidence quality': 'Additional income evidence required', 'Identity linkage': 'Verified', 'Consent': 'Synthetic consent fixture', 'Review': 'Pending analyst review', 'Core application': 'Not submitted', 'Disbursement': 'Not executed' }, 'warning');
score.related = [{ label: 'Customer workspace', section: 'customers', id: customer.id }, { label: 'Source ingestion', section: 'ingestion' }];
const cases = [
  record('demo-case-001', 'Deposit confirmed, posting pending', 'Payment', 'Open', 'Payments team', { 'Customer': 'Amina K. · demo', 'Assigned to': 'Demo analyst', 'Priority': 'High', 'Source reference': payment.id, 'Due': 'Today', 'Reason': 'Provider and ledger states disagree' }, 'warning'),
  record('demo-case-002', 'Additional income evidence required', 'Credit', 'Waiting', 'Risk team', { 'Customer': 'Issa D. · demo', 'Assigned to': 'Unassigned', 'Priority': 'Medium', 'Due': 'Today', 'Reason': 'Evidence incomplete' }, 'warning'),
  record('demo-case-003', 'Partner credential approaching expiry', 'Partner', 'Open', 'Partner operations', { 'Partner': 'Demo Market', 'Assigned to': 'Demo operator', 'Priority': 'Medium', 'Due': 'Tomorrow' }, 'warning'),
  record('demo-case-004', 'Alias reference successfully checked', 'Customer', 'Resolved', 'Support', { 'Customer': 'Nadia S. · demo', 'Assigned to': 'Demo analyst', 'Priority': 'Low', 'Reason': 'Directory and account references agree' }, 'success'),
];
cases[0].owners = payment.owners;
cases[0].related = payment.related?.filter((r) => r.section !== 'inbox').concat([{ label: 'Payment investigation', section: 'payments', id: payment.id }]);
const data: Partial<Record<SectionId, ConsoleRecord[]>> = {
  overview: cases, inbox: cases,
  customers: [customer, record('demo-customer-002', 'Issa D.', 'Personal', 'KYC review', 'Core', { 'Country': "Côte d’Ivoire", 'Phone': '+225 •• •• 6789', 'KYC level': 'Minimal', 'Accounts': 'Current', 'Agency': 'Abidjan · demo' }, 'warning'), record('demo-customer-003', 'Nadia S.', 'Personal', 'Active', 'Core', { 'Country': "Côte d’Ivoire", 'Phone': '+225 •• •• 9087', 'KYC level': 'Full', 'Accounts': 'Current + savings' }, 'success')],
  payments: [payment, record('demo-payment-002', 'Withdrawal to Mobile Money', 'Payout', 'Completed', 'Payment Gateway', { 'Customer': 'Nadia S. · demo', 'Amount': 'XOF 15,000', 'Provider': 'Provider B · synthetic', 'Financial posting': 'Completed' }, 'success'), record('demo-payment-003', 'Mobile Money deposit', 'Payin', 'Pending', 'Payment Gateway', { 'Customer': 'Issa D. · demo', 'Amount': 'XOF 10,000', 'Provider': 'Provider A · synthetic', 'Financial posting': 'Awaiting provider' }, 'warning')],
  credit: [score, record('demo-score-002', 'Nadia S. · credit assessment', 'Score only', 'Reviewed', 'Credit Intelligence', { 'Score': '845 / 1,200 · synthetic', 'Evidence quality': 'Complete', 'Core application': 'Not submitted', 'Disbursement': 'Not executed' }, 'success'), record('demo-score-003', 'Issa D. · credit assessment', 'Identity', 'Blocked', 'Credit Intelligence', { 'Score': 'Not evaluated', 'Identity linkage': 'Unverified', 'Disbursement': 'Not executed' }, 'danger')],
  partners: [record('demo-partner-001', 'Demo Market', 'Retail', 'Active', 'Core', { 'Tenant': 'demo-tenant', 'Environment': 'Sandbox', 'Countries': 'CI', 'Products': 'Score only', 'Credential status': 'Expiring in 14 days', 'Permissions': 'customer:read, score:request', 'Rate limit': '60 requests / minute', 'API secret': 'Never displayed', 'IP policy': 'Restricted' }, 'success'), record('demo-partner-002', 'Demo Distribution', 'Distribution', 'Onboarding', 'Core', { 'Tenant': 'demo-tenant', 'Environment': 'Sandbox', 'Credential status': 'Not issued', 'Countries': 'CI' }, 'warning')],
  ingestion: [record('demo-ingestion-001', 'Demo Market · monthly evidence', 'Batch', 'Completed', 'Credit Intelligence', { 'Source': 'Synthetic partner fixture', 'Received rows': '120', 'Accepted': '118', 'Quarantined': '2', 'Lineage': 'DEMO-BATCH-001', 'Consent basis': 'Fixture only', 'Freshness': '11 Sep 2026' }, 'success'), record('demo-ingestion-002', 'Demo Distribution · income file', 'Batch', 'Needs review', 'Credit Intelligence', { 'Source': 'Synthetic partner fixture', 'Reason': 'Schema validation failed', 'Rows processed': '0', 'Retry': 'Requires validated source correction' }, 'warning')],
  aliases: [record('demo-alias-001', '+225 •• •• 3456', 'Phone', 'Active', 'Alias service', { 'Customer': 'Amina K. · demo', 'Directory': 'Demo directory', 'Account reference': 'DEMO-ACCOUNT-001', 'Credential': 'Current account', 'Consistency': 'References match', 'Last sync': '11 Sep 2026 · synthetic' }, 'success'), record('demo-alias-002', '+225 •• •• 6789', 'Phone', 'Pending sync', 'Alias service', { 'Customer': 'Issa D. · demo', 'Account reference': 'DEMO-ACCOUNT-002', 'Consistency': 'Awaiting authoritative event' }, 'warning')],
  operations: ['Core API', 'Payment Gateway', 'Credit Intelligence', 'Alias service', 'Mobile BFF', 'Search index'].map((name, index) => record(`demo-service-${index}`, name, index === 5 ? 'Infrastructure' : 'Service', index === 5 ? 'Degraded' : 'Healthy', name, { 'Environment': 'Preview only', 'Observation': 'Synthetic health observation', 'Pending jobs': index === 5 ? '3' : '0', 'Source of truth': 'Owning service' }, index === 5 ? 'warning' : 'success')),
  configuration: [record('demo-config-001', 'Partner scoring availability', 'Feature flag', 'Enabled', 'Core', { 'Key': 'demo.partner_scoring', 'Effective value': 'Enabled', 'Scope': 'Sandbox / demo-tenant / CI', 'Version': '3', 'Last change': 'DEMO-CHANGE-001', 'Approval': 'Required for production' }, 'success'), record('demo-config-002', 'Minimum mobile version', 'Channel', 'Draft change', 'Mobile BFF', { 'Effective value': 'Demo 1.0.0', 'Proposed value': 'Demo 1.1.0', 'Scope': 'Sandbox', 'Approval': 'Pending', 'Version': '1' }, 'warning')],
  approvals: [record('demo-approval-001', 'Rotate Demo Market credential', 'Partner access', 'Pending approval', 'Partner operations', { 'Requested by': 'Demo requester', 'Requested scope': 'Sandbox / demo-tenant', 'Reason': 'Planned credential rotation', 'Risk': 'Medium', 'Before': 'Credential DEMO-OLD expires in 14 days', 'After': 'New scoped credential; old credential revoked after overlap', 'Execution': 'Not executed', 'Policy': 'Requester cannot approve their own change' }, 'warning'), record('demo-approval-002', 'Activate mobile version policy', 'Configuration', 'Pending approval', 'Product operations', { 'Requested by': 'Demo product manager', 'Requested scope': 'Sandbox', 'Before': 'Demo 1.0.0', 'After': 'Demo 1.1.0', 'Execution': 'Not executed' }, 'warning')],
  people: [record('demo-staff-001', 'Demo analyst', 'Support', 'Active', 'Keycloak', { 'Role': 'Support analyst', 'Tenant scope': 'demo-tenant', 'Agency': 'Demo Abidjan', 'Environment': 'Sandbox', 'Allowed': 'View customers, investigate cases', 'Not allowed': 'Disburse, edit balances, issue credentials', 'MFA': 'Synthetic verified session' }, 'success'), record('demo-staff-002', 'Demo reviewer', 'Risk', 'Active', 'Keycloak', { 'Role': 'Risk reviewer', 'Tenant scope': 'demo-tenant', 'Allowed': 'Review evidence', 'Not allowed': 'Execute disbursement', 'Environment': 'Sandbox' }, 'success')],
  audit: [record('demo-audit-001', 'customer.profile.viewed', 'Read', 'Recorded', 'Console audit', { 'Actor': 'Demo analyst', 'Target': 'DEMO-CUSTOMER-001', 'Tenant': 'demo-tenant', 'Correlation': 'DEMO-TRACE-001', 'Result': 'Success', 'Reason': 'Payment investigation', 'Integrity': 'Synthetic record; not a legal audit source' }, 'neutral'), record('demo-audit-002', 'credential.rotation.requested', 'Change request', 'Recorded', 'Core audit', { 'Actor': 'Demo requester', 'Target': 'DEMO-PARTNER-001', 'Tenant': 'demo-tenant', 'Result': 'Awaiting approval' }, 'neutral')],
  reports: [record('demo-report-001', 'Operations summary', 'Operations', 'Preview available', 'Console', { 'Sources': 'Synthetic investigation fixtures', 'Format': 'CSV', 'Date': '11 Sep 2026', 'Rows': '4', 'Freshness': 'Preview snapshot', 'Privacy': 'No production data' }, 'info'), record('demo-report-002', 'Payment exceptions', 'Payments', 'Preview available', 'Payment Gateway', { 'Sources': 'Synthetic payment fixtures', 'Format': 'CSV', 'Rows': '3', 'Privacy': 'No production data' }, 'info'), record('demo-report-003', 'Credit evidence quality', 'Risk', 'Preview available', 'Credit Intelligence', { 'Sources': 'Synthetic scoring fixtures', 'Format': 'CSV', 'Rows': '3', 'Privacy': 'No production data' }, 'info')],
};
export function previewData(section: SectionId): ConsoleData { const items = data[section] ?? []; return { state: 'preview', items, total: items.length, observedAt: time }; }
export function previewEnabled(env: Record<string, string | undefined> = process.env): boolean { return env.CONSOLE_PREVIEW_ENABLED === 'true' && ['preview', 'development'].includes(env.CONSOLE_ENV ?? ''); }
