'use client';
import Link from 'next/link';
import { useEffect, useState, type ReactNode } from 'react';
import { Icon, Logo } from './icons';
import { Badge, Modal } from './primitives';
import { sections, sectionFor, type ConsoleSession, type SectionId } from '../lib/console-model';
export function ConsoleShell({ section, preview, session, children }: { section: SectionId; preview: boolean; session?: ConsoleSession; children: ReactNode }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [dialog, setDialog] = useState<'search' | 'notifications' | 'profile' | null>(null);
  const [query, setQuery] = useState('');
  const root = preview ? '/preview' : '';
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setDialog('search'); } if (event.key === 'Escape') setMobileOpen(false); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
  return <><a className="skip-link" href="#main-content">Skip to content</a><button className={`mobile-backdrop ${mobileOpen ? 'open' : ''}`} aria-label="Close navigation" tabIndex={mobileOpen ? 0 : -1} onClick={() => setMobileOpen(false)} /><aside className={`sidebar ${mobileOpen ? 'open' : ''}`} id="console-navigation"><Link className="brand" href={`${root}/overview`}><Logo /><div>Mobicred<small>Operations console</small></div></Link><nav className="nav-scroll" aria-label="Main navigation">{['Workspace', 'Platform', 'Governance'].map((group) => <div key={group}><div className="nav-label">{group}</div>{sections.filter((item) => item.group === group).map((item) => <Link key={item.id} href={`${root}/${item.id}`} onClick={() => setMobileOpen(false)} aria-current={item.id === section ? 'page' : undefined} className={`nav-link ${item.id === section ? 'active' : ''}`}><Icon name={item.icon} size={16} /><span>{item.label}</span>{preview && item.id === 'inbox' && <span className="nav-count">4</span>}</Link>)}</div>)}<div className="nav-label">Connected tools</div><Link href={`${root}/operations`} className="nav-link"><Icon name="arrow" size={15} />Specialist workspaces</Link></nav><div className="sidebar-footer"><button className="profile-button" onClick={() => setDialog('profile')}><span className="avatar">{preview ? 'DA' : session ? session.name.slice(0, 2).toUpperCase() : '—'}</span><span>{preview ? 'Demo analyst' : session?.name ?? 'Staff workspace'}<small>{preview ? 'Design preview' : session ? 'Verified staff session' : 'Not signed in'}</small></span><Icon name="down" size={13} /></button></div></aside>
  <div className="workspace"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open navigation" aria-controls="console-navigation" aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}><Icon name="menu" /></button><button className="search-trigger" onClick={() => setDialog('search')}><Icon name="search" size={16} /><span>Search workspaces, records…</span><kbd>⌘ K</kbd></button><div className="top-actions"><button className="tenant" onClick={() => setDialog('profile')}>{preview ? 'Demo workspace' : session?.tenant ?? 'No tenant selected'} <Icon name="down" size={10} /></button><Badge tone={preview ? 'info' : 'neutral'}>{preview ? 'PREVIEW' : 'STAFF'}</Badge><button className={`icon-button ${preview ? 'notification-dot' : ''}`} aria-label="Notifications" onClick={() => setDialog('notifications')}><Icon name="bell" size={16} /></button><button className="icon-button" aria-label="Profile and access" onClick={() => setDialog('profile')}><Icon name="user" size={16} /></button></div></header><div className="context-bar"><div className="context-left"><Icon name={preview ? 'info' : 'lock'} size={12} /><strong>{preview ? 'Design preview' : 'Scoped staff workspace'}</strong><span>{preview ? 'Synthetic data only · no production actions' : 'No unverified data or automatic demo fallback'}</span></div><span>{preview ? '11 Sep 2026 · sample snapshot' : 'Status supplied by each owning service'}</span></div><main id="main-content" className="page"><div className="breadcrumb"><Link href={`${root}/overview`}>Console</Link><Icon name="chevron" size={10} /><span>{sectionFor(section).group}</span><Icon name="chevron" size={10} /><span>{sectionFor(section).label}</span></div>{children}<footer className="page-footer"><span><Icon name="shield" size={12} />{preview ? 'Synthetic preview · no financial actions' : 'Service-owned records. Permission-scoped access.'}</span><span>Mobicred Console <span aria-hidden="true">·</span> People. Data. Decisions.</span></footer></main></div>
  {dialog === 'search' && <Modal title="Find your workspace" close={() => setDialog(null)}><label className="sr-only" htmlFor="command-search">Search workspaces</label><input id="command-search" className="command-input" placeholder="Customers, reconciliation, partner access…" value={query} onChange={(event) => setQuery(event.target.value)} autoFocus /><div className="command-results">{sections.filter((s) => `${s.label} ${s.description}`.toLowerCase().includes(query.toLowerCase())).map((s) => <Link className="command-item" key={s.id} href={`${root}/${s.id}`} onClick={() => setDialog(null)}><Icon name={s.icon} />{s.label}<span>{s.group}</span></Link>)}</div><div className="panel-footer">Open a workspace to search its authorized records. <kbd>Esc to close</kbd></div></Modal>}
  {dialog === 'notifications' && <Modal title="Attention center" close={() => setDialog(null)}><div className="modal-body"><div className="notice"><Icon name="info" size={17} /><p>{preview ? 'These are synthetic notifications, not live service alerts.' : 'Notifications are unavailable until an authorized alert source is connected.'}</p></div>{preview && [['Payment reconciliation', 'Review the source-state mismatch.', 'payments'], ['Evidence review', 'Inspect the synthetic assessment.', 'credit'], ['Credential expiry', 'Review the partner credential lifecycle.', 'partners']].map(([title, detail, target]) => <Link key={title} className="alert-card" href={`${root}/${target}`} onClick={() => setDialog(null)}><span className="alert-icon"><Icon name="bell" size={15} /></span><div><h3>{title}</h3><p>{detail}</p></div><Icon name="arrow" size={13} /></Link>)}</div></Modal>}
  {dialog === 'profile' && <Modal title="Profile & access" close={() => setDialog(null)}><div className="modal-body"><dl className="detail-grid"><div className="detail-field"><dt>Identity</dt><dd>{preview ? 'Demo analyst' : session?.name ?? 'Not signed in'}</dd></div><div className="detail-field"><dt>Tenant</dt><dd>{preview ? 'demo-tenant' : session?.tenant ?? 'Not selected'}</dd></div><div className="detail-field"><dt>Role grants</dt><dd>{preview ? 'Preview only' : session?.roles.join(', ') || 'No verified grants'}</dd></div><div className="detail-field"><dt>Authentication</dt><dd>{preview ? 'Not a production session' : session ? 'Verified by staff identity provider' : 'Keycloak required'}</dd></div></dl><p className="muted">Tenant selection never grants access. Only verified identity claims authorize a tenant.</p><div className="modal-actions">{!preview && !session && <a className="button primary" href="/auth/login">Sign in with Keycloak</a>}{!preview && session && <form method="post" action="/auth/logout"><button className="button" type="submit">Sign out</button></form>}<Link className="button" href={`${root}/people`} onClick={() => setDialog(null)}>People & access</Link></div></div></Modal>}
  </>;
}
