'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ConsoleShell } from './console-shell';
import { Badge, EmptyState, Modal } from './primitives';
import { Icon } from './icons';
import { formatTime, statusTone, type ConsoleSession } from '../lib/console-model';
import { partnerScopes, type PartnerCredential, type PartnerPage } from '../lib/partner-model';
import './partner-workspace.css';

type Action = 'create_partner' | 'create_environment' | 'issue_credential' | 'rotate_credential' | 'revoke_credential';
type Receipt = { receiptId: string; partnerCode: string; tenantId: string; apiKey?: string; secretAvailable: boolean; replayed: boolean; credential?: PartnerCredential };
export function PartnerWorkspace({ data, session }: { data: PartnerPage; session?: ConsoleSession }) {
  const router = useRouter();
  const [operation, setOperation] = useState<{ action: Action; credential?: PartnerCredential } | null>(null);
  const [receipt, setReceipt] = useState<Receipt | null>(null); const [notice, setNotice] = useState(''); const [q, setQ] = useState(data.q);
  const [switching, setSwitching] = useState(false);
  const partner = data.partner;
  const context = session?.partnerContext;
  const tenants = context ? data.tenants.filter((t) => t.tenantId === context.tenantId) : data.tenants;
  const credentials = context ? data.credentials.filter((c) => c.tenantId === context.tenantId) : data.credentials;
  useEffect(() => { if (!receipt?.apiKey) return; const timeout = setTimeout(() => setReceipt(null), 120000); return () => clearTimeout(timeout); }, [receipt]);
  async function focus(tenantId: string) {
    if (!partner || switching) return; setSwitching(true);
    try { const response = await fetch('/api/partners/context', { method: 'POST', headers: { 'content-type': 'application/json', 'x-console-context-version': String(session?.contextVersion ?? 0) }, body: JSON.stringify({ partnerCode: partner.partnerCode, tenantId }) }); if (!response.ok) throw new Error(); window.location.assign(`/partners/${partner.partnerCode}`); }
    catch { setNotice('Partner context could not be changed. Reload and retry.'); setSwitching(false); }
  }
  function navigate(page: number) { const params = new URLSearchParams({ page: String(page), q, ...(partner ? { tab: data.tab } : {}) }); router.push(`/partners${partner ? `/${partner.partnerCode}` : ''}?${params}`); }
  return <ConsoleShell section="partners" preview={false} session={session}>
    <div className="page-heading"><div><div className="eyebrow">Partner operations</div><h1>{partner ? partner.displayName : 'Partners'}</h1><p>{partner ? 'Manage this relationship, API environments and customer connections.' : 'Manage Mobicred’s partner network from onboarding to API access.'}</p></div><div className="actions"><button className="button" onClick={() => router.refresh()}><Icon name="refresh" size={14} />Refresh</button>{data.permissions.canCreate && !context && <button className="button primary" onClick={() => setOperation({ action: partner ? 'create_environment' : 'create_partner' })}><Icon name="plus" size={14} />{partner ? 'Add environment' : 'New partner'}</button>}</div></div>
    {notice && <div className="notice" role="status">{notice}</div>}
    {data.state !== 'live' ? <section className="panel"><EmptyState state={data.state} detail={data.error} retry={() => router.refresh()} /></section> : !partner ? <section className="panel">
      <form className="toolbar" onSubmit={(e) => { e.preventDefault(); navigate(1); }}><label className="table-search"><Icon name="search" size={14} /><input aria-label="Search partners" value={q} maxLength={120} onChange={(e) => setQ(e.target.value)} placeholder="Search partner name or code…" /></label><button className="button">Search</button><span className="filter-summary">{data.meta.total} partners</span></form>
      <div className="table-scroll"><table><thead><tr><th>PARTNER</th><th>STATUS</th><th>COUNTRIES</th><th>UPDATED</th><th>WORKSPACE</th></tr></thead><tbody>{data.items.map((p) => <tr key={p.partnerCode}><td><Link className="record-link" href={`/partners/${p.partnerCode}`}><span className="record-avatar"><Icon name="building" size={16} /></span><span><strong>{p.displayName}</strong><small>{p.partnerCode}</small></span></Link></td><td><Badge tone={statusTone(p.status)}>{p.status}</Badge></td><td>{p.countryCodes.join(', ')}</td><td>{formatTime(p.updatedAt)}</td><td><Link className="text-link" href={`/partners/${p.partnerCode}`}>Open partner<Icon name="arrow" size={13} /></Link></td></tr>)}</tbody></table></div>
      {!data.items.length && <div className="partner-empty"><Icon name="building" size={30} /><h2>{data.q ? 'No matching partners' : 'Your partner network starts here'}</h2><p>Create a partner with its first environment and API access policy.</p>{data.permissions.canCreate && <button className="button primary" onClick={() => setOperation({ action: 'create_partner' })}>Create your first partner</button>}</div>}
      <Pagination page={data.meta.page} limit={data.meta.limit} total={data.meta.total} change={navigate} />
    </section> : <>
      <section className="partner-hero"><div className="partner-mark">{partner.displayName.slice(0, 2).toUpperCase()}</div><div><h2>{partner.displayName}</h2><p>{partner.legalName || 'Mobicred partner'} · <span className="partner-code">{partner.partnerCode}</span></p><p>{partner.countryCodes.join(' · ')}</p></div><div className="partner-hero-actions"><Badge tone={statusTone(partner.status)}>{partner.status}</Badge>{!context && <Link className="button" href="/partners">All partners</Link>}</div></section>
      <div className="partner-stats"><div className="panel partner-stat"><span>Environments in view</span><strong>{tenants.length}</strong></div><div className="panel partner-stat"><span>Credentials in view</span><strong>{credentials.length}</strong></div><div className="panel partner-stat"><span>Operational context</span><strong style={{ fontSize: 18 }}>{context ? context.environment : 'Partner overview'}</strong></div></div>
      {data.totals && (data.totals.credentials > data.credentials.length || data.totals.tenants > data.tenants.length || data.totals.policies > data.policies.length) && <div className="notice warning">This is a bounded inventory. Additional records exist in Core and are not shown here.</div>}
      <div className="section-tabs partner-tabs" aria-label="Partner views">{[['overview', 'Overview'], ['credentials', 'Credentials'], ['customers', 'Customers'], ['access', 'API access']].map(([id, title]) => <Link key={id} className={data.tab === id ? 'button primary' : 'button'} href={`/partners/${partner.partnerCode}?tab=${id}`}>{title}</Link>)}</div>
      {data.tab === 'overview' && <div className="partner-grid"><section className="panel"><div className="panel-header"><h2>API environments</h2><Badge>{tenants.length}</Badge></div>{tenants.map((t) => <div className="partner-environment" key={t.tenantId}><div><strong>{t.displayName}</strong><small>{t.environment} · <span className="partner-code">{t.tenantId}</span></small><Badge tone={statusTone(t.status)}>{t.status}</Badge></div><button className="button" disabled={switching || t.status !== 'ACTIVE' || context?.tenantId === t.tenantId} onClick={() => { void focus(t.tenantId); }}>{context?.tenantId === t.tenantId ? 'Current context' : 'Work in this context'}</button></div>)}{!tenants.length && <div className="partner-empty">No environment available.</div>}</section><section className="panel"><div className="panel-header"><h2>Partner details</h2></div><div className="panel-body"><dl className="partner-facts"><div><dt>Partner code</dt><dd className="partner-code">{partner.partnerCode}</dd></div><div><dt>Registered name</dt><dd>{partner.legalName || 'Not provided'}</dd></div><div><dt>Countries</dt><dd>{partner.countryCodes.join(', ')}</dd></div><div><dt>Updated</dt><dd>{formatTime(partner.updatedAt)}</dd></div></dl><p className="partner-help">Partner and environment records are managed by Core. Selecting a context changes the working view, not your Mobicred staff identity.</p><Link className="button" href={`/partners/${partner.partnerCode}?tab=customers`}>View customer connections<Icon name="arrow" size={13} /></Link></div></section></div>}
      {data.tab === 'credentials' && <section className="panel"><div className="panel-header"><div><h2>API credentials</h2><p className="partner-help">Secrets are shown once at issuance. Existing credentials show metadata only.</p></div><button className="button primary" disabled={!data.permissions.canManageCredentials || !tenants.some((t) => t.status === 'ACTIVE')} onClick={() => setOperation({ action: 'issue_credential' })}><Icon name="plus" size={14} />Issue credential</button></div><div className="table-scroll"><table><thead><tr><th>CREDENTIAL</th><th>ENVIRONMENT</th><th>STATUS</th><th>SCOPES</th><th>EXPIRY / LAST USED</th><th>ACTIONS</th></tr></thead><tbody>{credentials.map((c) => <tr key={c.credentialId}><td className="partner-code">{c.credentialKey}</td><td>{c.tenantId}</td><td><Badge tone={statusTone(c.status)}>{c.status}</Badge></td><td><div className="partner-policy-list">{c.scopes.map((s) => <span key={s}>{s}</span>)}</div></td><td>{c.expiresAt ? formatTime(c.expiresAt) : 'No expiry'}<small style={{ display: 'block' }}>Last used: {formatTime(c.lastUsedAt ?? undefined)}</small></td><td><div className="partner-table-actions"><button className="button" disabled={!data.permissions.canManageCredentials || c.status !== 'ACTIVE'} onClick={() => setOperation({ action: 'rotate_credential', credential: c })}>Rotate</button><button className="button" disabled={!data.permissions.canManageCredentials || c.status === 'REVOKED'} onClick={() => setOperation({ action: 'revoke_credential', credential: c })}>Revoke</button></div></td></tr>)}</tbody></table></div>{!credentials.length && <div className="partner-empty"><h2>No credentials yet</h2><p>Issue a scoped API credential for an active environment.</p></div>}</section>}
      {data.tab === 'customers' && <section className="panel"><form className="toolbar" onSubmit={(e) => { e.preventDefault(); navigate(1); }}><label className="table-search"><Icon name="search" size={14} /><input aria-label="Search partner customers" value={q} maxLength={120} onChange={(e) => setQ(e.target.value)} placeholder="Search partner customer reference…" /></label><button className="button">Search</button><span className="filter-summary">{data.customers?.meta.total ?? 0} customer connections</span></form><div className="table-scroll"><table><thead><tr><th>PARTNER REFERENCE</th><th>MOBICRED CUSTOMER</th><th>ENVIRONMENT</th><th>LINK STATUS</th><th>CUSTOMER STATUS</th><th>KYC</th></tr></thead><tbody>{data.customers?.items.map((c) => <tr key={c.referenceId}><td className="partner-code">{c.partnerCustomerRef}</td><td className="partner-code">{c.customerId}</td><td>{c.tenantId}</td><td><Badge tone={statusTone(c.status)}>{c.status}</Badge></td><td>{c.customerStatus || 'Not available'}</td><td>{c.kycLevel || 'Not available'}</td></tr>)}</tbody></table></div>{!data.customers?.items.length && <div className="partner-empty">No customer connections match this partner context.</div>}{data.customers && <Pagination {...data.customers.meta} change={navigate} />}</section>}
      {data.tab === 'access' && <div className="partner-grid"><section className="panel"><div className="panel-header"><h2>Access policies</h2></div><div className="panel-body">{data.policies.filter((p) => !context || p.tenantId === context.tenantId).map((p) => <div key={p.policyId} style={{ marginBottom: 24 }}><div className="row-line"><strong>{p.name}</strong><Badge tone={statusTone(p.status)}>{p.status}</Badge></div><p className="partner-help">Environment: {p.tenantId}</p><h3>Allowed source IPs</h3><div className="partner-policy-list">{p.ipAllowlist.map((ip) => <span key={ip}>{ip}</span>)}</div><h3>Allowed scopes</h3><div className="partner-policy-list">{p.scopes.map((s) => <span key={s}>{s}</span>)}</div></div>)}</div></section><section className="panel"><div className="panel-header"><h2>Connect a partner application</h2></div><div className="panel-body"><p>Use the partner’s public API endpoint with its own credentials, not a staff session.</p><pre className="partner-integration-code">{`GET /v1/partners/${partner.partnerCode}/customers\nX-Partner-Code: ${partner.partnerCode}\nX-Tenant-Id: <environment identifier>\nX-API-Key-Id: <credential key>\nX-API-Key: <secret shown at issuance>`}</pre><p className="partner-help">The environment policy checks source IP, credential status, expiry and scope. Deployments with request signing also require timestamp and HMAC headers. Use the integration helper documented in the repository; do not embed API secrets in browser or mobile bundles.</p><p className="partner-help">Partner customer lists include only that credential’s partner and environment. Staff continue using this separate Mobicred console.</p></div></section></div>}
    </>}
    {operation && session && <PartnerCommandDialog operation={operation} data={data} session={session} close={() => setOperation(null)} saved={(result) => { setOperation(null); setReceipt(result); setNotice(`Operation recorded · ${result.receiptId}`); if (!partner) router.push(`/partners/${result.partnerCode}?tab=credentials`); else router.refresh(); }} />}
    {receipt && <Modal title={receipt.apiKey ? 'Save the API secret now' : 'Operation recorded'} close={() => setReceipt(null)}><div className="modal-body">{receipt.apiKey ? <><p>This secret will not appear in the credential list and cannot be retrieved again. Store it in the partner’s secret manager.</p><div className="partner-secret" data-testid="issued-api-secret">{receipt.apiKey}</div><button className="button" style={{ marginTop: 12 }} onClick={async () => { try { await navigator.clipboard.writeText(receipt.apiKey!); setNotice('API secret copied. Store it securely.'); } catch { setNotice('Clipboard access was denied. Select the displayed secret manually.'); } }}>Copy API secret</button><p className="partner-help">This display closes automatically after two minutes.</p></> : <p>{receipt.replayed ? 'This request was already completed. Its secret is not retained. Inspect the credential before explicitly rotating or reissuing.' : 'The requested change has been recorded.'}</p>}<dl className="detail-grid"><div className="detail-field"><dt>Partner</dt><dd>{receipt.partnerCode}</dd></div><div className="detail-field"><dt>Environment</dt><dd>{receipt.tenantId}</dd></div><div className="detail-field"><dt>Receipt</dt><dd className="partner-code">{receipt.receiptId}</dd></div>{receipt.credential && <div className="detail-field"><dt>Credential key</dt><dd className="partner-code">{receipt.credential.credentialKey}</dd></div>}</dl><div className="modal-actions"><button className="button primary" onClick={() => setReceipt(null)}>{receipt.apiKey ? 'I have stored the secret' : 'Close'}</button></div></div></Modal>}
  </ConsoleShell>;
}
function Pagination({ page, limit, total, change }: { page: number; limit: number; total: number; change: (page: number) => void }) { return <div className="panel-footer"><span>{total} records · page {page} of {Math.max(1, Math.ceil(total / limit))}</span><div className="actions"><button className="button" disabled={page <= 1} onClick={() => change(page - 1)}>Previous</button><button className="button" disabled={page * limit >= total} onClick={() => change(page + 1)}>Next</button></div></div>; }

function PartnerCommandDialog({ operation, data, session, close, saved }: { operation: { action: Action; credential?: PartnerCredential }; data: PartnerPage; session: ConsoleSession; close: () => void; saved: (result: Receipt) => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [scopes, setScopes] = useState<string[]>(operation.credential?.scopes ?? ['customers:read']);
  const [attempted, setAttempted] = useState(false); const attempt = useRef<{ key: string; serialized: string } | null>(null);
  const creating = ['create_partner', 'create_environment'].includes(operation.action); const secretAction = ['issue_credential', 'rotate_credential'].includes(operation.action);
  const title = { create_partner: 'New partner', create_environment: 'Add environment', issue_credential: 'Issue API credential', rotate_credential: 'Rotate API credential', revoke_credential: 'Revoke API credential' }[operation.action];
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return;
    const form = new FormData(event.currentTarget);
    const fields = (name: string) => String(form.get(name) ?? '').trim();
    const partnerCode = data.partner?.partnerCode ?? fields('partnerCode');
    const tenantId = operation.credential?.tenantId ?? session.partnerContext?.tenantId ?? fields('tenantId');
    const command = { action: operation.action, partnerCode, tenantId, reason: fields('reason'), ...(creating ? { displayName: fields('displayName'), environment: fields('environment'), countryCodes: fields('countryCodes').split(',').map((s) => s.trim().toUpperCase()).filter(Boolean), ipAllowlist: fields('ipAllowlist').split(/[\n,]+/).map((s) => s.trim()).filter(Boolean), ...(fields('legalName') ? { legalName: fields('legalName') } : {}) } : {}), ...(operation.action !== 'revoke_credential' ? { scopes } : {}), ...(operation.credential ? { credentialKey: operation.credential.credentialKey } : {}), ...(secretAction && fields('expiresAt') ? { expiresAt: new Date(fields('expiresAt')).toISOString() } : {}) };
    const serialized = JSON.stringify(command);
    if (attempt.current && attempt.current.serialized !== serialized) { setError('This form already has an unconfirmed request. Retry it unchanged or close it and inspect the owner record before starting a different operation.'); return; }
    attempt.current ??= { serialized, key: crypto.randomUUID() };
    setBusy(true); setError(''); setAttempted(true);
    try {
      const response = await fetch('/api/partners/commands', { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': attempt.current.key, 'x-console-context-version': String(session.contextVersion ?? 0) }, body: attempt.current.serialized });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || 'The partner operation could not be completed.');
      if (typeof result.receiptId !== 'string' || result.partnerCode !== partnerCode || result.tenantId !== tenantId) throw new Error('The owner response could not be confirmed. Retry the same request.');
      saved(result as Receipt);
    } catch (err) { setError(err instanceof Error ? err.message : 'Outcome unconfirmed. Retry the same request.'); }
    finally { setBusy(false); }
  }
  return <Modal title={title} close={() => { if (!busy) close(); }} drawer><form className="drawer-body" onSubmit={submit}>
    <p>{creating ? 'Create native Core records and an explicit API access policy in one operation.' : `Partner: ${data.partner?.displayName} · ${operation.credential?.tenantId ?? session.partnerContext?.displayName ?? 'choose an environment below'}`}</p>
    {operation.action === 'create_partner' && <label className="form-field">Partner code<input name="partnerCode" required pattern="[a-z0-9][a-z0-9_-]{1,63}" placeholder="partner-code" maxLength={64} readOnly={attempted} /></label>}
    {creating && <><label className="form-field">Display name<input name="displayName" required minLength={2} maxLength={128} readOnly={attempted} /></label>{operation.action === 'create_partner' && <label className="form-field">Legal name (optional)<input name="legalName" maxLength={160} readOnly={attempted} /></label>}<h2 className="partner-form-section">{operation.action === 'create_partner' ? 'First API environment' : 'API environment'}</h2><label className="form-field">Environment identifier<input name="tenantId" required pattern="[a-z0-9][a-z0-9_-]{1,63}" placeholder="partner-sandbox" maxLength={64} readOnly={attempted} /></label><label className="form-field">Environment type<select name="environment" defaultValue="SANDBOX" disabled={busy}><option>SANDBOX</option><option>PRODUCTION</option></select></label><label className="form-field">Countries<input name="countryCodes" required defaultValue={data.partner?.countryCodes.join(', ') || 'CI'} placeholder="CI, SN" readOnly={attempted} /></label><label className="form-field">Allowed source IPs<textarea name="ipAllowlist" required placeholder="Partner server egress IPs or IPv4 CIDRs, one per line" readOnly={attempted} /></label><p className="partner-help">The existing API policy requires approved source IPs. Do not use universal network ranges.</p></>}
    {operation.action === 'issue_credential' && !session.partnerContext && <label className="form-field">API environment<select name="tenantId" required disabled={busy}><option value="">Select an active environment</option>{data.tenants.filter((t) => t.status === 'ACTIVE').map((t) => <option key={t.tenantId} value={t.tenantId}>{t.displayName} · {t.environment}</option>)}</select></label>}
    {operation.action !== 'revoke_credential' && <><h2 className="partner-form-section">API permissions</h2><div className="scope-grid">{partnerScopes.map((scope) => <label className="scope-option" key={scope}><input type="checkbox" checked={scopes.includes(scope)} disabled={busy || attempted} onChange={(e) => setScopes(e.target.checked ? [...scopes, scope] : scopes.filter((s) => s !== scope))} />{scope}</label>)}</div></>}
    {secretAction && <label className="form-field">Expiry (optional)<input name="expiresAt" type="datetime-local" readOnly={attempted} /></label>}
    {operation.credential && <div className="partner-form-warning">{operation.action === 'rotate_credential' ? 'Rotation immediately revokes the previous credential. Its replacement secret is shown once.' : 'Revocation prevents future API calls using this credential.'}<p className="partner-code">{operation.credential.credentialKey}</p></div>}
    <label className="form-field">Reason<textarea name="reason" required minLength={10} maxLength={1000} placeholder="Why is this partner change needed? Do not paste secrets." readOnly={attempted} /></label>
    {error && <div className="notice warning" role="alert">{error}</div>}
    <p className="partner-help">Your staff identity, the partner/environment and the command receipt are recorded. Secrets are never stored in audit records.</p>
    <div className="modal-actions"><button className="button" type="button" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={busy || (operation.action !== 'revoke_credential' && !scopes.length)}>{busy ? 'Submitting…' : attempted ? 'Retry same request' : title}</button></div>
  </form></Modal>;
}
