'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { ConsoleShell } from './console-shell';
import { Badge, EmptyState, Modal } from './primitives';
import { Icon } from './icons';
import { PartnerCommandDialog } from './partner-command-dialog';
import { formatTime, statusTone, type ConsoleSession } from '../lib/console-model';
import type { PartnerPage } from '../lib/partner-model';
import type { PartnerOperation, PartnerReceipt } from '../lib/partner-command-form';
import './partner-workspace.css';
import './operations-home.css';

export function PartnerWorkspace({ data, session, onboard = false }: { data: PartnerPage; session?: ConsoleSession; onboard?: boolean }) {
  const router = useRouter(); const partner = data.partner;
  const [operation, setOperation] = useState<PartnerOperation | null>(() => onboard && !partner && data.state === 'live' && data.permissions.canCreate ? { action: 'create_partner' } : null);
  const [receipt, setReceipt] = useState<PartnerReceipt | null>(null); const [notice, setNotice] = useState(''); const [q, setQ] = useState(data.q); const [switching, setSwitching] = useState(false);
  // Administration inventories follow the explicit route, never a hidden session filter.
  const { tenants, credentials } = data; const context = session?.partnerContext;
  useEffect(() => { if (!receipt?.apiKey) return; const timeout = setTimeout(() => setReceipt(null), 120000); return () => clearTimeout(timeout); }, [receipt]);
  function closeOperation() { setOperation(null); if (onboard) router.replace('/partners', { scroll: false }); }
  async function focus(tenantId: string) {
    if (!partner || switching) return; setSwitching(true);
    try { const response = await fetch('/api/partners/context', { method: 'POST', headers: { 'content-type': 'application/json', 'x-console-context-version': String(session?.contextVersion ?? 0) }, body: JSON.stringify({ partnerCode: partner.partnerCode, tenantId }) }); if (!response.ok) throw new Error(); window.location.assign(`/partners/${partner.partnerCode}`); }
    catch { setNotice('The operational filter could not be changed. Reload and retry.'); setSwitching(false); }
  }
  function navigate(page: number) { const params = new URLSearchParams({ page: String(page), q, ...(partner ? { tab: data.tab } : {}) }); router.push(`/partners${partner ? `/${partner.partnerCode}` : ''}?${params}`); }
  const isCurrent = (tenantId: string) => context?.partnerCode === partner?.partnerCode && context?.tenantId === tenantId;
  return <ConsoleShell section="partners" preview={false} session={session}>
    <div className="page-heading"><div><div className="eyebrow">Global partner administration</div><h1>{partner ? partner.displayName : 'Partners'}</h1><p>{partner ? 'Manage this partner’s environments, API credentials and customer connections.' : 'Onboard and administer Mobicred’s partner network. No partner selection is required.'}</p></div><div className="actions"><button className="button" onClick={() => router.refresh()}><Icon name="refresh" size={14} />Refresh</button>{data.permissions.canCreate && <button className="button primary" disabled={data.state !== 'live'} onClick={() => setOperation({ action: partner ? 'create_environment' : 'create_partner' })}><Icon name="plus" size={14} />{partner ? 'Add environment' : 'New partner'}</button>}</div></div>
    {context && <div className="admin-scope-note"><strong>Partner administration stays global</strong><p>Your operational filter remains {context.partnerName} · {context.displayName}. You can onboard and manage other partners here without switching accounts or changing that filter.</p></div>}
    {notice && <div className="notice" role="status">{notice}</div>}
    {data.state !== 'live' ? <section className="panel"><EmptyState state={data.state} detail={data.error} retry={() => router.refresh()} /><div className="panel-footer"><Link className="text-link" href="/overview">Return to operations</Link><span>No substitute or preview data is shown.</span></div></section> : !partner ? <section className="panel">
      <form className="toolbar" onSubmit={(event) => { event.preventDefault(); navigate(1); }}><label className="table-search"><Icon name="search" size={14} /><input aria-label="Search partners" value={q} maxLength={120} onChange={(event) => setQ(event.target.value)} placeholder="Search partner name or code…" /></label><button className="button">Search</button><span className="filter-summary">{data.meta.total} partners</span></form>
      <div className="table-scroll"><table><thead><tr><th>PARTNER</th><th>STATUS</th><th>COUNTRIES</th><th>UPDATED</th><th>ADMINISTRATION</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.partnerCode}><td><Link className="record-link" href={`/partners/${item.partnerCode}`}><span className="record-avatar"><Icon name="building" size={16} /></span><span><strong>{item.displayName}</strong><small>{item.partnerCode}</small></span></Link></td><td><Badge tone={statusTone(item.status)}>{item.status}</Badge></td><td>{item.countryCodes.join(', ')}</td><td>{formatTime(item.updatedAt)}</td><td><Link className="text-link" href={`/partners/${item.partnerCode}`}>Open partner<Icon name="arrow" size={13} /></Link></td></tr>)}</tbody></table></div>
      {!data.items.length && <div className="partner-empty"><Icon name="building" size={30} /><h2>{data.q ? 'No matching partners' : 'Your partner network starts here'}</h2><p>Register a partner with its first API environment and access policy. Credentials are issued separately after creation.</p>{data.permissions.canCreate && <button className="button primary" onClick={() => setOperation({ action: 'create_partner' })}>Create your first partner</button>}</div>}
      <Pagination {...data.meta} change={navigate} />
    </section> : <>
      <section className="partner-hero"><div className="partner-mark">{partner.displayName.slice(0, 2).toUpperCase()}</div><div><h2>{partner.displayName}</h2><p>{partner.legalName || 'Mobicred partner'} · <span className="partner-code">{partner.partnerCode}</span></p><p>{partner.countryCodes.join(' · ')}</p></div><div className="partner-hero-actions"><Badge tone={statusTone(partner.status)}>{partner.status}</Badge><Link className="button" href="/partners">All partners</Link>{data.permissions.canCreate && <Link className="button" href="/partners?onboard=1">New partner</Link>}</div></section>
      <div className="partner-stats"><div className="panel partner-stat"><span>API environments loaded</span><strong>{tenants.length}</strong></div><div className="panel partner-stat"><span>Credentials loaded</span><strong>{credentials.length}</strong></div><div className="panel partner-stat"><span>Administration target</span><strong style={{ fontSize: 18 }}>{partner.partnerCode}</strong></div></div>
      {data.totals && (data.totals.credentials > credentials.length || data.totals.tenants > tenants.length || data.totals.policies > data.policies.length) && <div className="notice warning">This is a bounded inventory. Additional records exist and are not shown here.</div>}
      <div className="section-tabs partner-tabs" aria-label="Partner views">{[['overview', 'Overview'], ['credentials', 'Credentials'], ['customers', 'Customers'], ['access', 'API access']].map(([id, title]) => <Link key={id} className={data.tab === id ? 'button primary' : 'button'} aria-current={data.tab === id ? 'page' : undefined} href={`/partners/${partner.partnerCode}?tab=${id}`}>{title}</Link>)}</div>
      {data.tab === 'overview' && <div className="partner-grid"><section className="panel"><div className="panel-header"><div><h2>API environments</h2><p className="partner-help">Select an environment only when you need to filter operational work.</p></div><Badge>{tenants.length}</Badge></div>{tenants.map((environment) => <div className="partner-environment" key={environment.tenantId}><div><strong>{environment.displayName}</strong><small>{environment.environment} · <span className="partner-code">{environment.tenantId}</span></small><Badge tone={statusTone(environment.status)}>{environment.status}</Badge></div><button className="button" disabled={switching || environment.status !== 'ACTIVE' || isCurrent(environment.tenantId)} onClick={() => { void focus(environment.tenantId); }}>{isCurrent(environment.tenantId) ? 'Current context' : 'Work in this context'}</button></div>)}{!tenants.length && <div className="partner-empty">No API environment has been configured for this partner.</div>}</section><section className="panel"><div className="panel-header"><h2>Partner details</h2></div><div className="panel-body"><dl className="partner-facts"><div><dt>Partner code</dt><dd className="partner-code">{partner.partnerCode}</dd></div><div><dt>Registered name</dt><dd>{partner.legalName || 'Not provided'}</dd></div><div><dt>Countries</dt><dd>{partner.countryCodes.join(', ')}</dd></div><div><dt>Updated</dt><dd>{formatTime(partner.updatedAt)}</dd></div></dl><p className="partner-help">You administer this partner as Mobicred staff. Its API applications use separate credentials and do not share your console session.</p><Link className="button" href={`/partners/${partner.partnerCode}?tab=customers`}>View customer connections<Icon name="arrow" size={13} /></Link></div></section></div>}
      {data.tab === 'credentials' && <section className="panel"><div className="panel-header"><div><h2>API credentials</h2><p className="partner-help">All environments for this partner. Secrets are shown only at issuance.</p></div><button className="button primary" disabled={!data.permissions.canManageCredentials || partner.status !== 'ACTIVE' || !tenants.some((environment) => environment.status === 'ACTIVE')} onClick={() => setOperation({ action: 'issue_credential' })}><Icon name="plus" size={14} />Issue credential</button></div>{!data.permissions.canManageCredentials && <p className="partner-help panel-body">Your role permits viewing metadata, but not issuing, rotating or revoking credentials.</p>}<div className="table-scroll"><table><thead><tr><th>CREDENTIAL</th><th>ENVIRONMENT</th><th>STATUS</th><th>SCOPES</th><th>EXPIRY / LAST USED</th><th>ACTIONS</th></tr></thead><tbody>{credentials.map((credential) => <tr key={credential.credentialId}><td className="partner-code">{credential.credentialKey}</td><td>{credential.tenantId}</td><td><Badge tone={statusTone(credential.status)}>{credential.status}</Badge></td><td><div className="partner-policy-list">{credential.scopes.map((scope) => <span key={scope}>{scope}</span>)}</div></td><td>{credential.expiresAt ? formatTime(credential.expiresAt) : 'No expiry'}<small style={{ display: 'block' }}>Last used: {formatTime(credential.lastUsedAt ?? undefined)}</small></td><td><div className="partner-table-actions"><button className="button" disabled={!data.permissions.canManageCredentials || partner.status !== 'ACTIVE' || credential.status !== 'ACTIVE'} onClick={() => setOperation({ action: 'rotate_credential', credential })}>Rotate</button><button className="button" disabled={!data.permissions.canManageCredentials || credential.status === 'REVOKED'} onClick={() => setOperation({ action: 'revoke_credential', credential })}>Revoke</button></div></td></tr>)}</tbody></table></div>{!credentials.length && <div className="partner-empty"><h2>No credentials yet</h2><p>Issue a scoped API credential for an active environment. No credential is required to administer this partner from the console.</p></div>}</section>}
      {data.tab === 'customers' && <section className="panel"><form className="toolbar" onSubmit={(event) => { event.preventDefault(); navigate(1); }}><label className="table-search"><Icon name="search" size={14} /><input aria-label="Search partner customers" value={q} maxLength={120} onChange={(event) => setQ(event.target.value)} placeholder="Search partner customer reference…" /></label><button className="button">Search</button><span className="filter-summary">{data.customers?.meta.total ?? 0} customer connections · all partner environments</span></form><div className="table-scroll"><table><thead><tr><th>PARTNER REFERENCE</th><th>MOBICRED CUSTOMER</th><th>ENVIRONMENT</th><th>LINK STATUS</th><th>CUSTOMER STATUS</th><th>KYC</th></tr></thead><tbody>{data.customers?.items.map((customer) => <tr key={customer.referenceId}><td className="partner-code">{customer.partnerCustomerRef}</td><td className="partner-code">{customer.customerId}</td><td>{customer.tenantId}</td><td><Badge tone={statusTone(customer.status)}>{customer.status}</Badge></td><td>{customer.customerStatus || 'Not available'}</td><td>{customer.kycLevel || 'Not available'}</td></tr>)}</tbody></table></div>{!data.customers?.items.length && <div className="partner-empty">No customer connections match this partner and search.</div>}{data.customers && <Pagination {...data.customers.meta} change={navigate} />}</section>}
      {data.tab === 'access' && <div className="partner-grid"><section className="panel"><div className="panel-header"><h2>Access policies</h2></div><div className="panel-body">{data.policies.map((policy) => <div key={policy.policyId} style={{ marginBottom: 24 }}><div className="row-line"><strong>{policy.name}</strong><Badge tone={statusTone(policy.status)}>{policy.status}</Badge></div><p className="partner-help">Environment: {policy.tenantId}</p><h3>Allowed source IPs</h3><div className="partner-policy-list">{policy.ipAllowlist.map((ip) => <span key={ip}>{ip}</span>)}</div><h3>Allowed scopes</h3><div className="partner-policy-list">{policy.scopes.map((scope) => <span key={scope}>{scope}</span>)}</div></div>)}</div></section><section className="panel"><div className="panel-header"><h2>Partner application integration</h2></div><div className="panel-body"><p>These credentials belong to the partner’s backend application, not to your staff console.</p><pre className="partner-integration-code">{`GET /v1/partners/${partner.partnerCode}/customers\nX-Partner-Code: ${partner.partnerCode}\nX-Tenant-Id: <environment identifier>\nX-API-Key-Id: <credential key>\nX-API-Key: <secret shown at issuance>`}</pre><p className="partner-help">The API checks source IP, status, expiry and scope. Request-signing deployments also require timestamp and HMAC headers. Never embed API secrets in a browser or mobile bundle.</p></div></section></div>}
    </>}
    {operation && session && <PartnerCommandDialog operation={operation} data={data} session={session} close={closeOperation} saved={(result) => { setOperation(null); setReceipt(result); setNotice(`Operation recorded · ${result.receiptId}`); if (!partner) router.push(`/partners/${result.partnerCode}?tab=credentials`); else router.refresh(); }} />}
    {receipt && <Modal title={receipt.apiKey ? 'Save the API secret now' : 'Operation recorded'} close={() => setReceipt(null)}><div className="modal-body">{receipt.apiKey ? <><p>Store this secret in the partner’s secret manager. It cannot be retrieved again.</p><div className="partner-secret" data-testid="issued-api-secret">{receipt.apiKey}</div><button className="button" style={{ marginTop: 12 }} onClick={async () => { try { await navigator.clipboard.writeText(receipt.apiKey!); setNotice('API secret copied. Store it securely.'); } catch { setNotice('Clipboard access was denied. Select the displayed secret manually.'); } }}>Copy API secret</button><p className="partner-help">This display closes automatically after two minutes.</p></> : <p>{receipt.replayed ? 'This operation was already completed. Its secret is not retained; inspect the credential before deliberately rotating or reissuing.' : 'The requested change has been recorded.'}</p>}<dl className="detail-grid"><div className="detail-field"><dt>Partner</dt><dd>{receipt.partnerCode}</dd></div><div className="detail-field"><dt>Environment</dt><dd>{receipt.tenantId}</dd></div><div className="detail-field"><dt>Receipt</dt><dd className="partner-code">{receipt.receiptId}</dd></div>{receipt.credential && <div className="detail-field"><dt>Credential key</dt><dd className="partner-code">{receipt.credential.credentialKey}</dd></div>}</dl><div className="modal-actions"><button className="button primary" onClick={() => setReceipt(null)}>{receipt.apiKey ? 'I have stored the secret' : 'Close'}</button></div></div></Modal>}
  </ConsoleShell>;
}
function Pagination({ page, limit, total, change }: { page: number; limit: number; total: number; change: (page: number) => void }) { return <div className="panel-footer"><span>{total} records · page {page} of {Math.max(1, Math.ceil(total / limit))}</span><div className="actions"><button className="button" disabled={page <= 1} onClick={() => change(page - 1)}>Previous</button><button className="button" disabled={page * limit >= total} onClick={() => change(page + 1)}>Next</button></div></div>; }
